# Copyright (C) 2024 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

services:
  worker-finqa-agent:
    image: opea/agent:latest
    container_name: finqa-agent-endpoint
    volumes:
      - ${TOOLSET_PATH}:/home/user/tools/
      - ${PROMPT_PATH}:/home/user/prompts/
    ports:
      - "9095:9095"
    ipc: host
    environment:
      ip_address: ${ip_address}
      strategy: react_llama
      with_memory: false
      recursion_limit: ${recursion_limit_worker}
      llm_engine: vllm
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      llm_endpoint_url: ${LLM_ENDPOINT_URL}
      model: ${LLM_MODEL_ID}
      temperature: ${TEMPERATURE}
      max_new_tokens: ${MAX_TOKENS}
      stream: false
      tools: /home/user/tools/finqa_agent_tools.yaml
      custom_prompt: /home/user/prompts/finqa_prompt.py
      require_human_feedback: false
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      REDIS_URL_VECTOR: $REDIS_URL_VECTOR
      REDIS_URL_KV: $REDIS_URL_KV
      TEI_EMBEDDING_ENDPOINT: $TEI_EMBEDDING_ENDPOINT
      port: 9095

  worker-research-agent:
    image: opea/agent:latest
    container_name: research-agent-endpoint
    volumes:
      - ${TOOLSET_PATH}:/home/user/tools/
      - ${PROMPT_PATH}:/home/user/prompts/
    ports:
      - "9096:9096"
    ipc: host
    environment:
      ip_address: ${ip_address}
      strategy: react_llama
      with_memory: false
      recursion_limit: 25
      llm_engine: vllm
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      llm_endpoint_url: ${LLM_ENDPOINT_URL}
      model: ${LLM_MODEL_ID}
      stream: false
      tools: /home/user/tools/research_agent_tools.yaml
      custom_prompt: /home/user/prompts/research_prompt.py
      require_human_feedback: false
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      FINNHUB_API_KEY: ${FINNHUB_API_KEY}
      FINANCIAL_DATASETS_API_KEY: ${FINANCIAL_DATASETS_API_KEY}
      port: 9096

  supervisor-react-agent:
    image: opea/agent:latest
    container_name: supervisor-agent-endpoint
    depends_on:
      - worker-finqa-agent
      - worker-research-agent
    volumes:
      - ${TOOLSET_PATH}:/home/user/tools/
      - ${PROMPT_PATH}:/home/user/prompts/
    ports:
      - "9090:9090"
    ipc: host
    environment:
      ip_address: ${ip_address}
      strategy: react_llama
      with_memory: true
      recursion_limit: ${recursion_limit_supervisor}
      llm_engine: vllm
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      llm_endpoint_url: ${LLM_ENDPOINT_URL}
      model: ${LLM_MODEL_ID}
      temperature: ${TEMPERATURE}
      max_new_tokens: ${MAX_TOKENS}
      stream: true
      tools: /home/user/tools/supervisor_agent_tools.yaml
      custom_prompt: /home/user/prompts/supervisor_prompt.py
      require_human_feedback: false
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      WORKER_FINQA_AGENT_URL: $WORKER_FINQA_AGENT_URL
      WORKER_RESEARCH_AGENT_URL: $WORKER_RESEARCH_AGENT_URL
      DOCSUM_ENDPOINT: $DOCSUM_ENDPOINT
      REDIS_URL_VECTOR: $REDIS_URL_VECTOR
      REDIS_URL_KV: $REDIS_URL_KV
      TEI_EMBEDDING_ENDPOINT: $TEI_EMBEDDING_ENDPOINT
      port: 9090

  vllm-service:
    image: ${REGISTRY:-opea}/vllm-rocm:${TAG:-latest}
    container_name: docsum-vllm-service
    ports:
      - "${FINANCEAGENT_VLLM_SERVICE_PORT:-8081}:8011"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HUGGINGFACEHUB_API_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
      VLLM_USE_TRITON_FLASH_ATTENTION: 0
      PYTORCH_JIT: 0
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://${HOST_IP}:${FINANCEAGENT_VLLM_SERVICE_PORT:-8081}/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 100
    volumes:
      - "${MODEL_CACHE:-./data}:/data"
    shm_size: 20G
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri/:/dev/dri/
    cap_add:
      - SYS_PTRACE
    group_add:
      - video
    security_opt:
      - seccomp:unconfined
      - apparmor=unconfined
    command: "--model ${LLM_MODEL_ID} --swap-space 16 --disable-log-requests --dtype float16 --tensor-parallel-size 4 --host 0.0.0.0 --port 8011 --num-scheduler-steps 1 --distributed-executor-backend \"mp\""
    ipc: host

  docsum-llm-textgen:
    image: ${REGISTRY:-opea}/llm-docsum:${TAG:-latest}
    container_name: docsum-llm-server
    depends_on:
      vllm-service:
        condition: service_healthy
    ports:
      - "${DOCSUM_LLM_SERVER_PORT}:9000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LLM_ENDPOINT: ${DOCSUM_LLM_ENDPOINT}
      HUGGINGFACEHUB_API_TOKEN: ${DOCSUM_HUGGINGFACEHUB_API_TOKEN}
      MAX_INPUT_TOKENS: ${DOCSUM_MAX_INPUT_TOKENS}
      MAX_TOTAL_TOKENS: ${DOCSUM_MAX_TOTAL_TOKENS}
      LLM_MODEL_ID: ${DOCSUM_LLM_MODEL_ID}
      DocSum_COMPONENT_NAME: "DocSum_COMPONENT_NAME:-OpeaDocSumvLLM"
      LOGFLAG: ${LOGFLAG:-False}
    restart: unless-stopped

  agent-ui:
    image: opea/agent-ui:latest
    container_name: agent-ui
    environment:
      host_ip: ${host_ip}
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
    ports:
      - "5175:8080"
    ipc: host

  tei-embedding-serving:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    container_name: tei-embedding-serving
    entrypoint: /bin/sh -c "apt-get update && apt-get install -y curl && text-embeddings-router --json-output --model-id ${EMBEDDING_MODEL_ID} --auto-truncate"
    ports:
      - "${TEI_EMBEDDER_PORT:-10221}:80"
    volumes:
      - "./data:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      host_ip: ${host_ip}
      HF_TOKEN: ${HF_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${host_ip}:${TEI_EMBEDDER_PORT}/health"]
      interval: 10s
      timeout: 6s
      retries: 48

  redis-vector-db:
    image: redis/redis-stack:7.2.0-v9
    container_name: redis-vector-db
    ports:
      - "${REDIS_PORT1:-6379}:6379"
      - "${REDIS_PORT2:-8001}:8001"
    environment:
      - no_proxy=${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 3
      start_period: 10s

  redis-kv-store:
    image: redis/redis-stack:7.2.0-v9
    container_name: redis-kv-store
    ports:
      - "${REDIS_PORT3:-6380}:6379"
      - "${REDIS_PORT4:-8002}:8001"
    environment:
      - no_proxy=${no_proxy}
      - http_proxy=${http_proxy}
      - https_proxy=${https_proxy}
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 3
      start_period: 10s

  dataprep-redis-finance:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-redis-server-finance
    depends_on:
      redis-vector-db:
        condition: service_healthy
      redis-kv-store:
        condition: service_healthy
      tei-embedding-serving:
        condition: service_healthy
    ports:
      - "${DATAPREP_PORT:-6007}:5000"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      DATAPREP_COMPONENT_NAME: ${DATAPREP_COMPONENT_NAME}
      REDIS_URL_VECTOR: ${REDIS_URL_VECTOR}
      REDIS_URL_KV: ${REDIS_URL_KV}
      TEI_EMBEDDING_ENDPOINT: ${TEI_EMBEDDING_ENDPOINT}
      LLM_ENDPOINT: ${LLM_ENDPOINT}
      LLM_MODEL: ${LLM_MODEL}
      HUGGINGFACEHUB_API_TOKEN: ${HF_TOKEN}
      HF_TOKEN: ${HF_TOKEN}
      LOGFLAG: true
