# Copyright (C) 2024 Intel Corporation
# Copyright (c) 2024 Advanced Micro Devices, Inc.
# SPDX-License-Identifier: Apache-2.0

services:
  codegen-vllm-service:
    image: ${REGISTRY:-opea}/vllm-rocm:${TAG:-latest}
    container_name: codegen-vllm-service
    ports:
      - "${CODEGEN_VLLM_SERVICE_PORT:-8081}:8011"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      HUGGINGFACEHUB_API_TOKEN: ${CODEGEN_HUGGINGFACEHUB_API_TOKEN}
      HF_TOKEN: ${CODEGEN_HUGGINGFACEHUB_API_TOKEN}
      HF_HUB_DISABLE_PROGRESS_BARS: 1
      HF_HUB_ENABLE_HF_TRANSFER: 0
      WILM_USE_TRITON_FLASH_ATTENTION: 0
      PYTORCH_JIT: 0
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://${HOST_IP}:${CODEGEN_VLLM_SERVICE_PORT:-8028}/health || exit 1" ]
      interval: 10s
      timeout: 10s
      retries: 100
    volumes:
      - "./data:/data"
    shm_size: 20G
    devices:
      - /dev/kfd:/dev/kfd
      - /dev/dri/:/dev/dri/
    cap_add:
      - SYS_PTRACE
    group_add:
      - video
    security_opt:
      - seccomp:unconfined
      - apparmor=unconfined
    command: "--model ${CODEGEN_LLM_MODEL_ID} --swap-space 16 --disable-log-requests --dtype float16 --tensor-parallel-size 4 --host 0.0.0.0 --port 8011 --num-scheduler-steps 1 --distributed-executor-backend \"mp\""
    ipc: host
  codegen-llm-server:
    image: ${REGISTRY:-opea}/llm-textgen:${TAG:-latest}
    container_name: codegen-llm-server
    depends_on:
      codegen-vllm-service:
        condition: service_healthy
    ports:
      - "${CODEGEN_LLM_SERVICE_PORT:-9000}:9000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      LLM_ENDPOINT: ${CODEGEN_VLLM_ENDPOINT}
      LLM_MODEL_ID: ${CODEGEN_LLM_MODEL_ID}
      HUGGINGFACEHUB_API_TOKEN: ${CODEGEN_HUGGINGFACEHUB_API_TOKEN}
      HF_TOKEN: ${CODEGEN_HUGGINGFACEHUB_API_TOKEN}
      LLM_COMPONENT_NAME: "OpeaTextGenService"
    restart: unless-stopped
  codegen-backend-server:
    image: ${REGISTRY:-opea}/codegen:${TAG:-latest}
    container_name: codegen-backend-server
    depends_on:
      - codegen-llm-server
    ports:
      - "${CODEGEN_BACKEND_SERVICE_PORT:-7778}:7778"
    environment:
      no_proxy: ${no_proxy}
      https_proxy: ${https_proxy}
      http_proxy: ${http_proxy}
      MEGA_SERVICE_HOST_IP: ${CODEGEN_MEGA_SERVICE_HOST_IP}
      LLM_SERVICE_HOST_IP: ${HOST_IP}
      LLM_SERVICE_PORT: ${CODEGEN_LLM_SERVICE_PORT}
      RETRIEVAL_SERVICE_HOST_IP: ${RETRIEVAL_SERVICE_HOST_IP}
      REDIS_RETRIEVER_PORT: ${REDIS_RETRIEVER_PORT}
      TEI_EMBEDDING_HOST_IP: ${TEI_EMBEDDING_HOST_IP}
      EMBEDDER_PORT: ${EMBEDDER_PORT}
    ipc: host
    restart: always
  codegen-ui-server:
    image: ${REGISTRY:-opea}/codegen-gradio-ui:${TAG:-latest}
    container_name: codegen-ui-server
    depends_on:
      - codegen-backend-server
    ports:
      - "5173:5173"
    environment:
      - no_proxy=${no_proxy}
      - https_proxy=${https_proxy}
      - http_proxy=${http_proxy}
      - BASIC_URL=${CODEGEN_BACKEND_SERVICE_URL}
      - MEGA_SERVICE_PORT=${CODEGEN_BACKEND_SERVICE_PORT}
      - host_ip=${HOST_IP}
      - DATAPREP_ENDPOINT=${DATAPREP_ENDPOINT}
      - DATAPREP_REDIS_PORT=${DATAPREP_REDIS_PORT}
    ipc: host
    restart: always
  redis-vector-db:
    image: redis/redis-stack:7.2.0-v9
    container_name: redis-vector-db
    ports:
      - "${REDIS_DB_PORT}:${REDIS_DB_PORT}"
      - "${REDIS_INSIGHTS_PORT}:${REDIS_INSIGHTS_PORT}"
  dataprep-redis-server:
    image: ${REGISTRY:-opea}/dataprep:${TAG:-latest}
    container_name: dataprep-redis-server
    depends_on:
      - redis-vector-db
    ports:
      - "${DATAPREP_REDIS_PORT}:5000"
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      REDIS_URL: ${REDIS_URL}
      REDIS_HOST: ${host_ip}
      INDEX_NAME: ${INDEX_NAME}
      HUGGINGFACEHUB_API_TOKEN: ${CODEGEN_HUGGINGFACEHUB_API_TOKEN}
      LOGFLAG: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/v1/health_check || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
  tei-embedding-serving:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-1.5
    container_name: tei-embedding-serving
    entrypoint: /bin/sh -c "apt-get update && apt-get install -y curl && text-embeddings-router --json-output --model-id ${EMBEDDING_MODEL_ID} --auto-truncate"
    ports:
      - "${TEI_EMBEDDER_PORT:-12000}:80"
    volumes:
      - "./data:/data"
    shm_size: 1g
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      host_ip: ${host_ip}
      HF_TOKEN: ${CODEGEN_HUGGINGFACEHUB_API_TOKEN}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 10s
      timeout: 6s
      retries: 48
  tei-embedding-server:
    image: ${REGISTRY:-opea}/embedding:${TAG:-latest}
    container_name: tei-embedding-server
    ports:
      - "${EMBEDDER_PORT:-10201}:6000"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      TEI_EMBEDDING_ENDPOINT: ${TEI_EMBEDDING_ENDPOINT}
      EMBEDDING_COMPONENT_NAME: "OPEA_TEI_EMBEDDING"
    depends_on:
      tei-embedding-serving:
        condition: service_healthy
    restart: unless-stopped
  retriever-redis:
    image: ${REGISTRY:-opea}/retriever:${TAG:-latest}
    container_name: retriever-redis
    depends_on:
      - redis-vector-db
    ports:
      - "${REDIS_RETRIEVER_PORT}:${REDIS_RETRIEVER_PORT}"
    ipc: host
    environment:
      no_proxy: ${no_proxy}
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      REDIS_URL: ${REDIS_URL}
      REDIS_DB_PORT: ${REDIS_DB_PORT}
      REDIS_INSIGHTS_PORT: ${REDIS_INSIGHTS_PORT}
      REDIS_RETRIEVER_PORT: ${REDIS_RETRIEVER_PORT}
      INDEX_NAME: ${INDEX_NAME}
      TEI_EMBEDDING_ENDPOINT: ${TEI_EMBEDDING_ENDPOINT}
      HUGGINGFACEHUB_API_TOKEN: ${CODEGEN_HUGGINGFACEHUB_API_TOKEN}
      LOGFLAG: ${LOGFLAG}
      RETRIEVER_COMPONENT_NAME: ${RETRIEVER_COMPONENT_NAME:-OPEA_RETRIEVER_REDIS}
    restart: unless-stopped

networks:
  default:
    driver: bridge
